// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-hOceJcgNi9Lrd9Y3YZDBcOzYnIbK4k',
    appId: '1:701147182658:web:d30f6bf008271d647a5fdb',
    messagingSenderId: '701147182658',
    projectId: 'auth-app-9678a',
    authDomain: 'auth-app-9678a.firebaseapp.com',
    storageBucket: 'auth-app-9678a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgA0NPV3-oko7FMIl_0pPCce62entTUik',
    appId: '1:701147182658:android:df1fa6147043d6b57a5fdb',
    messagingSenderId: '701147182658',
    projectId: 'auth-app-9678a',
    storageBucket: 'auth-app-9678a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ngfu9iCA0lHneqPJbr7PrTDrzPEznjk',
    appId: '1:701147182658:ios:399978d20c0715437a5fdb',
    messagingSenderId: '701147182658',
    projectId: 'auth-app-9678a',
    storageBucket: 'auth-app-9678a.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ngfu9iCA0lHneqPJbr7PrTDrzPEznjk',
    appId: '1:701147182658:ios:50198e2c156b30577a5fdb',
    messagingSenderId: '701147182658',
    projectId: 'auth-app-9678a',
    storageBucket: 'auth-app-9678a.appspot.com',
    iosBundleId: 'com.example.authApp.RunnerTests',
  );
}
